### GET a Post
POST {{BASE_URL}}/ws/
Content-Type: text/xml

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
                  xmlns:soap="https://io.github.untalsanders/ws/soap">
    <soapenv:Header/>
    <soapenv:Body>
        <soap:getPostRequest>
            <soap:id>3</soap:id>
        </soap:getPostRequest>
    </soapenv:Body>
</soapenv:Envelope>